### ISSUE TITLE
preserveEmptySpace on string formatter have different behaviour from documentation

### ISSUE THREAD

**Issue by cimasim89** [cimasim89/flat-file-creator#139]

**Comment by cimasim89** [comment]
Hi @kael-shipman, I hope you are well, I would like to discuss with you for a moment how to manage this condition. We do this check:
```
if (map.preserveEmptySpace || map.preserveEmptySpace === undefined) {
	str = str.trim()
}
```
it trims the string when the field is 'undefined' and the condition maybe should be reversed, in the documentation we have written that by default spaces are preserved, I would like to resolve this discrepancy, do you think the correct behaviour is the to not preserver or is better follow the documentation?

Good day Kael.

**Comment by kael-shipman** [comment]
Looks like you resolved this, and I agree with your resolution! Better to default to trimming.

**Comment by cimasim89** [comment]
Sorry @kael-shipman,
I do it in rush, but I had one project down. Then I choose to give priority to existing code behaviour.

**Comment by kael-shipman** [comment]
No problem! Looks good to me.
