### ISSUE TITLE
Convert project to Typescript

### ISSUE THREAD

**Issue by kael-shipman** [cimasim89/flat-file-creator#14]
Per my comments in PR #13 , I think it would be very easy and also very useful to convert this project to typescript. It requires no additional system-level dependencies and will make the project both more robust and also better documented.

I'm happy to do the work (which will not take very long at all) if you approve of the idea.

**Comment by kael-shipman** [comment]
I started in on this even though you hadn't given me the go-ahead just to see what it would take. I'm almost there, and have pushed my work-in-progress to the new `typescript` branch.

I've changed almost nothing of the actual functionality except where necessary to make typescript cooperate. However, I had to restructure a bit. Feel free to look at it, but also feel free to ignore it until I'm done and you can see what it looks like at the end.

**Comment by cimasim89** [comment]
Hi Kael sorry but with the different time zones I missed your proposal, in any case it's great! It's a step that will definitely give us many advantages.
