### ISSUE TITLE
Add `default` property to field spec to allow for optional fields (with defaults)

### ISSUE THREAD

**Issue by kael-shipman** [cimasim89/flat-file-creator#16]
I believe currently the tool expects all fields to be present. I tested this by trying to leave out a few fields when creating an entry, and it worked ok for string fields, but not for date, which produced an error.

I propose we add a `default` property to mitigate this, such that if the `default` property is present, then the field is implicitly optional, and defaults to the given value.

For example:

```ts
const rowDef = [
  {
    name: "fullName",
    size: 25,
    type: "string",
  },
  {
    name: "dob",
    size: 20,
    type: "date",
    default: null,
  },
  {
    name: "optIn",
    size: 1,
    type: "integer",
    default: 0,
  }
];
```

In the above, if the `dob` field is not given, then `null` is used, and if the `optIn` field is not given, then `0` is used. If the `fullName` field is not given, however, an exception will be thrown.

**Comment by cimasim89** [comment]
in relation to this point, I think there are some fields that you have already rightly considered optional, but i think about adding also all those for which we provide a default value, see for example `rowEnd`. Then there are the two fields related to `stringFieldFormatter`, in fact the tests work well without adding `?` but these types will be displayed by who will use the library, perhaps for consistency would be better to mark these optional too.
Last but not least, the `straight` option, an error of mine in choosing the correct English word to indicate how it works... we must consider using the correct one `strict`, but should choose if we correctly highlight this change, or allow to use of both?

**Comment by cimasim89** [comment]
oh, now I get it, it's interesting to add this behaviour, we can think of a fill of empty characters, or one indicated, for the missing attributes or allow you to set a 'default'.

**Comment by kael-shipman** [comment]
I'm going to change the name of this issue to reflect the above unless you say otherwise.
